# Generated by Django 5.2 on 2026-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('finished', 'Забег закончен'), ('in_progress', 'Забег начат'), ('init', 'Забег инициализирован')], default='init'),
        ),
    ]
