# Generated by Django 5.2 on 2026-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_athleteinfo_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Забег инициализирован'), ('finished', 'Забег закончен'), ('in_progress', 'Забег начат')], default='init'),
        ),
    ]
