# Generated by Django 5.2 on 2026-02-03 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_alter_athleteinfo_weight_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(899)]),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Забег начат'), ('finished', 'Забег закончен'), ('init', 'Забег инициализирован')], default='init'),
        ),
    ]
