# Generated by Django 5.2 on 2026-02-05 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Забег инициализирован'), ('in_progress', 'Забег начат'), ('finished', 'Забег закончен')], default='init'),
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_run.run')),
            ],
        ),
    ]
