# Generated by Django 5.2 on 2026-02-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_alter_run_status_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Забег начат'), ('finished', 'Забег закончен'), ('init', 'Забег инициализирован')], default='init'),
        ),
    ]
