# Generated by Django 5.2 on 2026-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0020_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('finished', 'Забег закончен'), ('init', 'Забег инициализирован'), ('in_progress', 'Забег начат')], default='init'),
        ),
    ]
